init
Postamentovich/indexUpdateBot pull request #1
Opened 2021-03-07 21:58 UTC by GhostMayor

2021-03-08 15:51 UTC, martis-git commented
@GhostMayor 

![image](https://user-images.githubusercontent.com/42924400/110345042-36771180-803f-11eb-8334-84f51c15e5bb.png)

![image](https://user-images.githubusercontent.com/42924400/110345125-4c84d200-803f-11eb-8e8c-4491c3cfa476.png)

2021-03-08 15:55 UTC, martis-git requested changes
![image](https://user-images.githubusercontent.com/42924400/110345684-e9476f80-803f-11eb-8d63-1aebaac4c2b5.png)

2021-03-08 15:55 UTC, martis-git commented on bot.ts
> +bot.on("text", async (ctx: TelegrafContext) => {
А разве типы не автоматом тут подхватываются? `bot` же типизирован по идее

2021-03-08 15:55 UTC, martis-git commented on package.json
> +    "start": "node index.js",
1. Там ты в `index.js` (который уже index.ts!) явно импортируешь bot.js (который уже bot.ts)
2. А точно ли будет это нормально запускаться в heroku без сборки? Мб если уж завозишь ts, сразу сделать `"start": "ts-node index.ts"` ?

2021-03-13 11:23 UTC, martis-git commented
@GhostMayor

2021-03-13 11:26 UTC, Postamentovich commented
Тут уже не свести

2021-03-13 11:27 UTC, closed without merging